# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: youtube rest framework

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# name: Do things every 10 minutes
# on:
#   schedule:
#     - cron: "*/10 * * * *"

jobs: 
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache pip
      uses: actions/cache@v2
      with:
      
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase
        python -m playwright install
        sudo apt-get install libegl1\
            libopus0\
            libwoff1\
            libharfbuzz-icu0\
            libgstreamer-plugins-base1.0-0\
            libgstreamer-gl1.0-0\
            libgstreamer-plugins-bad1.0-0\
            libopenjp2-7\
            libwebpdemux2\
            libenchant1c2a\
            libhyphen0\
            libgles2\
            gstreamer1.0-libav
        python -m pip install --upgrade pip
        pip install python_jwt
        pip install gcloud
        pip install sseclient
        pip install pycrypto
        pip install requests-toolbelt
        pip install ez_setup
        # pip install flake8 
        if [ -f requirements.txt ]; then pip install -r requirements.txt --upgrade; fi
        
        #     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Uploading to IBM 
      env:
        APIKEY: ${{ secrets.IBMCLOUDAPIKEY }}
      run: |
        curl -sL https://raw.githubusercontent.com/IBM-Cloud/ibm-cloud-developer-tools/master/linux-installer/idt-installer | bash
        ibmcloud login --apikey lLKLaMq1Z0EjlAwvg9o9KylKYwRmm2-acobna4WI4xQX -r eu-gb
        ibmcloud cf install
        ibmcloud target --cf
        ls
        ibmcloud cf push ytserver
        ibmcloud cf logs ytserver --recent
